import Head from "next/head";
import { Inter } from "next/font/google";
import Room from "@/components/Room/Room";
import VideoPlayer from "@/components/VideoPlayer/ReactPlayerWrapper";

export const VideoPlayerWrapper = VideoPlayer;

export default function Lobby() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Room />
      </main>
    </>
  );
}
